### ISSUE TITLE
Use sqlx for less insane sql.query functions

### ISSUE THREAD

**Issue by lil5** [averageflow/goscope#59]
**Docs:** https://jmoiron.github.io/sqlx/

**Github:** https://github.com/jmoiron/sqlx

# Major additional concepts are:

-  Marshal rows into structs (with embedded struct support), maps, and slices
-  Named parameter support including prepared statements
-  Get and Select to go quickly from query to struct/slice

```go
// Named queries, using `:name` as the bindvar.  Automatic bindvar support
// which takes into account the dbtype based on the driverName on sqlx.Open/Connect
_, err = db.NamedExec(`INSERT INTO person (first_name,last_name,email) VALUES (:first,:last,:email)`, 
        map[string]interface{}{
            "first": "Bin",
            "last": "Smuth",
            "email": "bensmith@allblacks.nz",
    })
```

# 1. In queries

Giving an array to the value of an in query is supported in sqlx!

```go
    var levels = []int{4, 6, 7}
    query, args, err := sqlx.In("SELECT * FROM users WHERE level IN (?);", levels)
     
    // sqlx.In returns queries with the `?` bindvar, we can rebind it for our backend
    query = db.Rebind(query)
    rows, err := db.Query(query, args...)
```

# 2. Named queries

This removes the cluster f*ck of `?, ?, ?, ?, ?, ?, ?`.

```go
    arg := map[string]interface{}{
        "published": true,
        "authors": []{8, 19, 32, 44},
    }
    query, args, err := sqlx.Named("SELECT * FROM articles WHERE published=:published AND author_id IN (:authors)", arg)
    query, args, err := sqlx.In(query, args...)
    query = db.Rebind(query)
    db.Query(query, args...)
```

# 3. It's not another goqu 🍰 

This in my eyes still fulfills the wish to stick to plain sql, as it is not a query builder in the traditional sense.

**Comment by averageflow** [comment]
@lil5 While I understand your idea, I simply do not see the advantage on this, given the fact that this is an extra dependency, and a big one, to a project like GoScope that is supposed to be already a dependency to other projects.

As for the points:
- Marshal rows into structs (with embedded struct support), maps, and slices: This is already supported in the standard database/sql package.
- Named parameter support including prepared statements: Using MySQL is indeed restricted to `?` parameter, but if you use PostgreSQL you can do numbered parameters with `$1 $2 $3`.
- Get and Select to go quickly from query to struct/slice: I like to have the error handling in my hands.
- Giving an array to the value of an in query: That is a big point in favour of `sqlx` , but the underlying implementation is nothing more than a strings.Join, something which I already do in many applications.

Overall it is a nice package, but is something that I do not want to use, since anything that you do to avoid SQL is simply a denial move and adding extra dependencies and layers between me and the database IMHO.
