### ISSUE TITLE
Add another DB support

### ISSUE THREAD

**Issue by Alexfilus** [averageflow/goscope#6]
Looks like exactly what I search! 
But I'm using PostgreSQL. Any plan to support another DBMS?

**Comment by averageflow** [comment]
This should not be too difficult, if you have some experience with postgre please port the setup.sql and we can work from there

**Comment by Alexfilus** [comment]
Yes, but for example in crud.go MySQL connection is hardcoded. 
It should be some kind of abstraction.

**Comment by averageflow** [comment]
Last commit improves DB abstraction. I am not experienced in postgre so am trying to see if i can get a test environment setup.

**Comment by averageflow** [comment]
@Alexfilus could you try with the latest version, to see what else we need to finish postgre support?

**Comment by WLun001** [comment]
Possible for MongoDB?

**Comment by averageflow** [comment]
> Possible for MongoDB?

@WLun001 Initially i had no plans for mongodb, however i do see that may be a useful addition. I have no experience with it so i cant start working towards it. The way i made it now, you can change the connection to mongodb instead of mysql in the env file and start writing some of statements here and there so you do different INSERT and SELECt statements for retrieving and inserting info. Once we have that we can abstract things to a cleaner repository pattern that will be able to deal with any db we have written for, but for that we need some if statements first with the code. Contributions are more than welcome.

**Comment by averageflow** [comment]
Help is now wanted to test out the postgre syntax. The reository pattern has now been implemented and could further be extended to anything that returns `*sql.Rows`

**Comment by averageflow** [comment]
> Help is now wanted to test out the postgre syntax. The reository pattern has now been implemented and could further be extended to anything that returns `*sql.Rows`

@Alexfilus

**Comment by Alexfilus** [comment]
I have some ideas, I want to try it at the next weekend

**Comment by yuriizinets** [comment]
It would be nice to make it more database agnostic.
F.e., I'd like to setup small, simple proxy pass app with goscope middleware. But I forced to connect huge database in terms of my app (MySQL/PostgeSQL) instead of small sqlite.
I'd like to keep my app as simple, as possible and don't want to setup additional DB for that "one-liner".

I hope it's possible :)

**Comment by averageflow** [comment]
> It would be nice to make it more database agnostic.
> 
> F.e., I'd like to setup small, simple proxy pass app with goscope middleware. But I forced to connect huge database in terms of my app (MySQL/PostgeSQL) instead of small sqlite.
> 
> I'd like to keep my app as simple, as possible and don't want to setup additional DB for that "one-liner".
> 
> 
> 
> I hope it's possible :)

As you can see the repository pattern has been implemented, now we just need a translation of the setup.sql file to sqlite and to add one more statement to the repository pattern functions, matter of 30 minutes at most, feel free to make a PR or wait until i have some time since i would also like sqlite support

**Comment by averageflow** [comment]
@yuriizinets you can now try the latest release. This has been merged in #27
